### ISSUE TITLE
Add setup.py to project

### ISSUE THREAD

**Issue by nikolaj-funartech** [brightway-lca/bw_processing#35]
Maybe we could add a dummy `setup.py` file for backward compatibility?

**Comment by cmutel** [comment]
Sorry, it  took me a bit of time to adapt, but the following works well:

1. Make sure you have `build` installed in your venv
2. `python -m build`

This will build the package, both sdist and a wheel.

Are there other things you want `setup.py` for? `setup.cfg` has support [since 2016](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html), not really sure we need support stuff from before then :)

**Comment by nikolaj-funartech** [comment]
You're right but people are used to `setup.py` and then there are strange things happening when not using it... Python tools...
